name: Backport labeled merged pull requests
on:
  pull_request:
    types: [ closed ]
  issue_comment:
    types: [ created ]
jobs:
  build:
    name: Create backport PRs
    if: >
      github.event_name == 'pull_request' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '/backport')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # required to find all branches
          fetch-depth: 0
      - name: Create backport PRs
        uses: zeebe-io/backport-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_workspace: ${{ github.workspace }}
          version: master
